services:
  frontend:
    build: frontend
    stdin_open: true
    container_name: compose_dev_frontend
    volumes:
      - ./frontend/app:/root/angular/TWOUITTERE/src/app
    ports:
      - 4202:4200
    networks:
      - angular-express
    restart: always
    depends_on:
      - backend

  backend:
    build: backend
    container_name: compose_dev_backend
    volumes:
      - ./backend/app:/root/TWOUITTERE
    ports:
      - 3002:3000
    networks:
      - express-mongo
      - angular-express
    restart: always
    depends_on:
      - database

  database:
    image: mongo:latest
#    command: ["--quiet"]
    command: ["--logpath", "/dev/null"]
    container_name: compose_dev_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: Twouittere
    volumes:
      - database_volume:/data/db
    expose:
      - 27017
    networks:
      - express-mongo
    restart: always

networks:
  angular-express:
  express-mongo:

volumes:
  database_volume:
#    name: compose_dev_database_volume

