services:
  frontend:
    build: frontend
    stdin_open: true
    container_name: compose_EI2ANGNOD_frontend
    ports:
      - 4200:4200
    networks:
      - angular-express
    restart: always
    depends_on:
      - backend

  backend:
    build: backend
    container_name: compose_EI2ANGNOD_backend
    ports:
      - 8888:8888
    networks:
      - express-mongo
      - angular-express
    restart: always
    depends_on:
      - database

  database:
    build: database
    command: ["--quiet"]
#    command: ["--logpath", "/dev/null"]
    container_name: compose_EI2ANGNOD_database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
#      MONGO_INITDB_DATABASE: OnlineSales
    expose:
      - 27017
    networks:
      - express-mongo
    restart: always

networks:
  angular-express:
  express-mongo:

