FROM debian:buster

RUN apt-get update \
	&& apt-get install -y curl git

RUN { curl -fsSL https://deb.nodesource.com/setup_14.x \
	| bash - ;} \
	&& apt-get install -y nodejs

RUN npm install -g @angular/cli@latest

RUN mkdir --parents /root/angular

WORKDIR /root/angular

EXPOSE 4200
