FROM debian:latest

RUN apt-get update \
	&& apt-get install -y curl git

RUN { curl -fsSL https://deb.nodesource.com/setup_14.x \
	| bash - ;} \
	&& apt-get install -y nodejs

RUN npm install -g @angular/cli@latest

WORKDIR /root

EXPOSE 4200
