FROM debian:buster

RUN apt-get update \
	&& apt-get install -y wget gnupg procps

RUN { wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc \
	| apt-key add - ;}

RUN { echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" \
	| tee /etc/apt/sources.list.d/mongodb-org-4.4.list ;}

RUN apt-get update \
	&& apt-get install -y mongodb-org

EXPOSE 27017

