services:
  frontend:
    build: frontend
    ports:
      - 8443:443
    stdin_open: true
    container_name: compose_prod_frontend
    restart: always
    networks:
      - httpd-express
    depends_on:
      - backend

  backend:
    container_name: compose_prod_backend
    restart: always
    build: backend
    ports:
      - 3001:3000
    depends_on:
      - database
    networks:
      - express-mongo
      - httpd-express

  database:
    container_name: compose_prod_mongo
    restart: always
    image: mongo:latest
    volumes:
      - compose_prod_database_volume:/data/db
    networks:
      - express-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
networks:
  httpd-express:
  express-mongo:
volumes:
  compose_prod_database_volume:
